[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

; Belangrijk: pak de library uit de repo-root
lib_extra_dirs = ../..

lib_deps =
  bblanchon/ArduinoJson@^7
  adafruit/Adafruit NeoPixel@^1.12.0
  